INSERT INTO video (id, url, titulo) VALUES (1, 'https://example.com/video1', 'Introduction to Java');
INSERT INTO video (id, url, titulo) VALUES (2, 'https://example.com/video2', 'Advanced Java Concepts');
INSERT INTO video (id, url, titulo) VALUES (3, 'https://example.com/video3', 'Java for Beginners');
INSERT INTO video (id, url, titulo) VALUES (4, 'https://example.com/video4', 'Understanding OOP in Java');
INSERT INTO video (id, url, titulo) VALUES (5, 'https://example.com/video5', 'Java Streams Explained');
INSERT INTO video (id, url, titulo) VALUES (6, 'https://example.com/video6', 'Building REST APIs with Java');
INSERT INTO video (id, url, titulo) VALUES (7, 'https://example.com/video7', 'Java Exception Handling');
INSERT INTO video (id, url, titulo) VALUES (8, 'https://example.com/video8', 'Java Collections Framework');
INSERT INTO video (id, url, titulo) VALUES (9, 'https://example.com/video9', 'Multithreading in Java');
INSERT INTO video (id, url, titulo) VALUES (10, 'https://example.com/video10', 'Java Design Patterns');
INSERT INTO n_video (id, url, titulo) VALUES (1, 'https://example.com/video1', 'Introduction to Java');
INSERT INTO n_video (id, url, titulo) VALUES (2, 'https://example.com/video2', 'Advanced Java Concepts');
INSERT INTO n_video (id, url, titulo) VALUES (3, 'https://example.com/video3', 'Java for Beginners');
INSERT INTO n_video (id, url, titulo) VALUES (4, 'https://example.com/video4', 'Understanding OOP in Java');
INSERT INTO n_video (id, url, titulo) VALUES (5, 'https://example.com/video5', 'Java Streams and Lambdas');
INSERT INTO n_video (id, url, titulo) VALUES (6, 'https://example.com/video6', 'Building REST APIs with Java');
INSERT INTO n_video (id, url, titulo) VALUES (7, 'https://example.com/video7', 'Java Exception Handling');
INSERT INTO n_video (id, url, titulo) VALUES (8, 'https://example.com/video8', 'Java Collections Framework');
INSERT INTO n_video (id, url, titulo) VALUES (9, 'https://example.com/video9', 'Multithreading in Java');
INSERT INTO n_video (id, url, titulo) VALUES (10, 'https://example.com/video10', 'Java Design Patterns');